[versions]
agp = "8.9.3"
v4version = "19.0.0"
minSdk = "21"
targetSdk = "35"
compileSdk = "36"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
support-v19 = { group = "com.android.support", name = "support-v4", version.ref = "v4version" }
